In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime
from datetime import timedelta

# Data Preprocessing (Average)

In [ ]:
# calculate average sentiment score for each day
# The dataset misses the tweets data from March 29 2020 to March 30 2020
twitter = pd.read_csv("/content/drive/MyDrive/AN6201/corona_tweets_04.csv",header=None)
d = datetime(year=2020,month=3,day=17)
twitter['Date']=d+timedelta(days=4)
twitter.columns=['ID','Sentiment','Date']
twitter.drop(columns=['ID'],inplace=True)
sentiment = twitter.groupby(twitter.Date).mean()
sentiment

Sentiment
Date                 
2020-03-21   0.027722

In [ ]:
# Sentiment Score from March 21 2020 to March 28 2020
for i in range(5,12):
  if i<=9:
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_0{i}.csv",header=None)
    df['Date']=d+timedelta(days=i)
    df.columns=['ID','Sentiment','Date']
    df.drop(columns=['ID'],inplace=True)
    df_score = df.groupby(df.Date).mean()
    sentiment = sentiment.append(df_score)
  else:
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_{i}.csv",header=None)
    df['Date']=d+timedelta(days=i)
    df.columns=['ID','Sentiment','Date']
    df.drop(columns=['ID'],inplace=True)
    df_score = df.groupby(df.Date).mean()
    sentiment = sentiment.append(df_score)
sentiment4_11 = sentiment.copy()
sentiment4_11

In [ ]:
pd.set_option('display.max_rows',10)

In [ ]:
# Sentiment Score from March 30 2020 to June 26 2020
d = datetime(year=2020,month=3,day=18)
for i in range(12,101):
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_{i}.csv",header=None)
    df['Date']=d+timedelta(days=i)
    df.columns=['ID','Sentiment','Date']
    df.drop(columns=['ID'],inplace=True)
    df_score = df.groupby(df.Date).mean()
    sentiment4_11 = sentiment4_11.append(df_score)
sentiment4_100 = sentiment4_11.copy()
sentiment4_100

Sentiment
Date                 
2020-03-21   0.027722
2020-03-22   0.043513
2020-03-23   0.020968
2020-03-24   0.025657
2020-03-25   0.032868
...               ...
2020-06-22   0.049518
2020-06-23   0.034758
2020-06-24   0.023805
2020-06-25   0.040488
2020-06-26   0.044650

[97 rows x 1 columns]

In [ ]:
# Sentiment Score from June 27 2020 to September 14 2020
d = datetime(year=2020,month=3,day=18)
for i in range(101,181):
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_{i}.csv",header=None)
    df['Date']=d+timedelta(days=i)
    df.columns=['ID','Sentiment','Date']
    df.drop(columns=['ID'],inplace=True)
    df_score = df.groupby(df.Date).mean()
    sentiment4_100 = sentiment4_100.append(df_score)
sentiment4_180 = sentiment4_100.copy()
sentiment4_180

In [ ]:
# Sentiment Score from September 15 2020 to November 24 2020
for i in range(181,252):
  if i == 223: # corona_tweets_223 lacks all the sentiment scores
    pass
  else:
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_{i}.csv",header=None)
    df['Date']=d+timedelta(days=i)
    df.columns=['ID','Sentiment','Date']
    df.drop(columns=['ID'],inplace=True)
    df_score = df.groupby(df.Date).mean()
    sentiment4_180 = sentiment4_180.append(df_score)
sentiment4_251 = sentiment4_180.copy()
sentiment4_251

Sentiment
Date                 
2020-03-21   0.027722
2020-03-22   0.043513
2020-03-23   0.020968
2020-03-24   0.025657
2020-03-25   0.032868
...               ...
2020-11-20   0.066100
2020-11-21   0.047689
2020-11-22   0.038419
2020-11-23   0.060244
2020-11-24   0.054402

[247 rows x 1 columns]

In [ ]:
sentiment4_251.to_csv("sentiment.csv")

In [ ]:
# Because the dataset lack the sentiment score for March 29 2020 and November 6 2020
# We check whether these two day has huge events related to covid-19
# And find out there is no. Therefore, we decided to take the average of the sentiment score
# for last day and next day

missing_days = {"Sentiment":[np.nan,np.nan]}
missing_days_index = [datetime(year=2020,month=3,day=29),datetime(year=2020,month=10,day=27)]
df_missing = pd.DataFrame(data = missing_days,index=missing_days_index)
df_missing

Sentiment
2020-03-29        NaN
2020-10-27        NaN

In [ ]:
sentiment = sentiment4_251.copy()
sentiment = sentiment.append(df_missing)
sentiment['Date'] = sentiment.index
sentiment['Sentiment_Score'] = sentiment['Sentiment']
sentiment.drop(columns=['Sentiment'],inplace=True)
sentiment.sort_index(inplace=True)
sentiment.index = range(len(sentiment))
sentiment

Date  Sentiment_Score
0   2020-03-21         0.027722
1   2020-03-22         0.043513
2   2020-03-23         0.020968
3   2020-03-24         0.025657
4   2020-03-25         0.032868
5   2020-03-26         0.049188
6   2020-03-27         0.045155
7   2020-03-28         0.067495
8   2020-03-29              NaN
9   2020-03-30         0.066099
10  2020-03-31         0.048198
11  2020-04-01         0.028267
12  2020-04-02         0.050594
13  2020-04-03         0.048836
14  2020-04-04         0.050547
15  2020-04-05         0.040489
16  2020-04-06         0.031689
17  2020-04-07         0.046688
18  2020-04-08         0.060005
19  2020-04-09         0.053490
20  2020-04-10         0.057782
21  2020-04-11         0.057677
22  2020-04-12         0.048541
23  2020-04-13         0.040094
24  2020-04-14         0.043745
25  2020-04-15         0.030612
26  2020-04-16         0.042433
27  2020-04-17         0.050992
28  2020-04-18         0.064072
29  2020-04-19         0.056478
30  2020-04-20         0.056889
31  2020-04-21         0.057966
32  2020-04-22         0.059583
33  2020-04-23         0.058517
34  2020-04-24         0.056242
35  2020-04-25         0.046758
36  2020-04-26         0.053726
37  2020-04-27         0.058183
38  2020-04-28         0.052746
39  2020-04-29         0.059621
40  2020-04-30         0.071291
41  2020-05-01         0.069175
42  2020-05-02         0.062954
43  2020-05-03         0.060488
44  2020-05-04         0.059309
45  2020-05-05         0.063185
46  2020-05-06         0.055172
47  2020-05-07         0.057394
48  2020-05-08         0.066793
49  2020-05-09         0.055685
50  2020-05-10         0.054579
51  2020-05-11         0.057516
52  2020-05-12         0.051398
53  2020-05-13         0.056094
54  2020-05-14         0.060261
55  2020-05-15         0.059555
56  2020-05-16         0.053311
57  2020-05-17         0.051490
58  2020-05-18         0.059107
59  2020-05-19         0.058882
60  2020-05-20         0.052185
61  2020-05-21         0.059353
62  2020-05-22         0.066655
63  2020-05-23         0.052494
64  2020-05-24         0.063041
65  2020-05-25         0.074633
66  2020-05-26         0.081773
67  2020-05-27         0.066634
68  2020-05-28         0.044773
69  2020-05-29         0.039000
70  2020-05-30         0.027254
71  2020-05-31         0.039001
72  2020-06-01         0.033906
73  2020-06-02         0.037608
74  2020-06-03         0.044990
75  2020-06-04         0.049810
76  2020-06-05         0.043676
77  2020-06-06         0.034852
78  2020-06-07         0.024029
79  2020-06-08         0.066314
80  2020-06-09         0.058230
81  2020-06-10         0.051726
82  2020-06-11         0.055296
83  2020-06-12         0.048955
84  2020-06-13         0.035541
85  2020-06-14        -0.018960
86  2020-06-15         0.039239
87  2020-06-16         0.055039
88  2020-06-17         0.056534
89  2020-06-18         0.040167
90  2020-06-19         0.042575
91  2020-06-20         0.035908
92  2020-06-21         0.045026
93  2020-06-22         0.049518
94  2020-06-23         0.034758
95  2020-06-24         0.023805
96  2020-06-25         0.040488
97  2020-06-26         0.044650
98  2020-06-27         0.038982
99  2020-06-28         0.065346
100 2020-06-29         0.048723
101 2020-06-30         0.039884
102 2020-07-01         0.048830
103 2020-07-02         0.051560
104 2020-07-03         0.078475
105 2020-07-04         0.047200
106 2020-07-05         0.031503
107 2020-07-06         0.020581
108 2020-07-07         0.040447
109 2020-07-08         0.040851
110 2020-07-09         0.038665
111 2020-07-10         0.044398
112 2020-07-11         0.052422
113 2020-07-12         0.056849
114 2020-07-13         0.063482
115 2020-07-14         0.062721
116 2020-07-15         0.043645
117 2020-07-16         0.029014
118 2020-07-17         0.043425
119 2020-07-18         0.062256
120 2020-07-19         0.046152
121 2020-07-20         0.049634
122 2020-07-21         0.054689
123 2020-07-22         0.053313
124 2020-0

In [ ]:
sentiment[sentiment['Date']=="2020-03-29"].index #8
sentiment[sentiment['Date']=="2020-10-27"].index #220

Int64Index([220], dtype='int64')

In [ ]:
sentiment['Sentiment_Score'][8] = (sentiment['Sentiment_Score'][7]+sentiment['Sentiment_Score'][9])/2
sentiment['Sentiment_Score'][220] = (sentiment['Sentiment_Score'][219]+sentiment['Sentiment_Score'][221])/2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
# Check whether fillna succesfully
sentiment.isnull().sum()

Date               0
Sentiment_Score    0
dtype: int64

In [ ]:
sentiment.to_csv("Sentiment_final.csv",index=False)

In [ ]:
sentiment = pd.read_csv("Sentiment_final.csv")
sentiment

Date  Sentiment_Score
0     2020/3/21         0.027722
1     2020/3/22         0.043513
2     2020/3/23         0.020968
3     2020/3/24         0.025657
4     2020/3/25         0.032868
..          ...              ...
244  2020/11/20         0.066100
245  2020/11/21         0.047689
246  2020/11/22         0.038419
247  2020/11/23         0.060244
248  2020/11/24         0.054402

[249 rows x 2 columns]

In [ ]:
sentiment[sentiment['Sentiment_Score']<0]

Date  Sentiment_Score
85 2020-06-14         -0.01896

In [ ]:
pd.set_option('display.max_rows',10)

In [ ]:
communications_services = pd.read_csv("Communication Services.csv",header=None)
communications_services.columns=['Date','communications services']
consumer_discretionary = pd.read_csv("Consumer Discretionary.csv",header=None)
consumer_discretionary.columns=['Date','consumer discretionary']
consumer_staples = pd.read_csv("Consumer Staples.csv",header=None)
consumer_staples.columns=['Date','consumer staples']
energy = pd.read_csv("Energy.csv",header=None)
energy.columns=['Date','energy']
financials = pd.read_csv("Financials.csv",header=None)
financials.columns=['Date','financials']
health_care = pd.read_csv("Health Care.csv",header=None)
health_care.columns=['Date','health care']
industrials = pd.read_csv("Industrials.csv",header=None)
industrials.columns=['Date','industrials']
information_technology = pd.read_csv("Information Technology.csv",header=None)
information_technology.columns=['Date','information technology']
materials = pd.read_csv("Materials.csv",header=None)
materials.columns=['Date','materials']
real_estate = pd.read_csv("Real Estate.csv",header=None)
real_estate.columns=['Date','real estate']
utilities = pd.read_csv("Utilities.csv",header=None)
utilities.columns=['Date','utilities']
price = pd.concat( [communications_services, consumer_discretionary, consumer_staples,
                 energy,financials,health_care,industrials,
                 information_technology,materials,real_estate,utilities], axis=1)
price = price.iloc[:,[0,1,3,5,7,9,11,13,15,17,19,21]]
price

Date  communications services  ...  real estate  utilities
0    2019/11/20                   176.25  ...       239.81     319.57
1    2019/11/21                   176.69  ...       236.48     318.39
2    2019/11/22                   176.92  ...       235.20     318.47
3    2019/11/25                   177.13  ...       235.33     317.30
4    2019/11/26                   177.77  ...       238.72     318.51
..          ...                      ...  ...          ...        ...
249  2020/11/16                   214.49  ...       233.38     338.09
250  2020/11/17                   213.59  ...       233.65     331.28
251  2020/11/18                   211.52  ...       229.74     324.87
252  2020/11/19                   212.39  ...       230.02     321.53
253  2020/11/20                   211.22  ...       228.51     321.68

[254 rows x 12 columns]

In [ ]:
communications_services[communications_services['Date'] == '2020/3/23'].index

Int64Index([83], dtype='int64')

In [ ]:
sentiment.dtypes

In [ ]:
sentiment.Date = pd.to_datetime(sentiment['Date'], errors='coerce')
sentiment.dtypes

Date               datetime64[ns]
Sentiment_Score           float64
dtype: object

In [ ]:
industry = price.iloc[83:254,]
industry.Date = pd.to_datetime(industry['Date'], errors='coerce')
industry.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


Date  communications services  ...  real estate  utilities
83 2020-03-23                   137.76  ...       158.62     227.75
84 2020-03-24                   145.77  ...       172.18     252.66
85 2020-03-25                   143.46  ...       179.92     259.84
86 2020-03-26                   152.14  ...       193.97     281.63
87 2020-03-27                   145.91  ...       193.83     283.10

[5 rows x 12 columns]

In [ ]:
industry.shape

(171, 12)

In [ ]:
test = pd.merge(left=industry, right=sentiment, how='left', left_on='Date', right_on='Date')
test.head()
test.to_csv("combine.csv",index=False)

# Pearson correlation coefficient

In [ ]:
industry_list = ['communications services', 'consumer discretionary',
       'consumer staples', 'energy', 'financials', 'health care',
       'industrials', 'information technology', 'materials', 'real estate',
       'utilities']
for i in industry_list:
  print(i)
  print(np.corrcoef(test[i].to_numpy(), test.Sentiment_Score))

communications services
[[1.         0.25827745]
 [0.25827745 1.        ]]
consumer discretionary
[[1.         0.19564159]
 [0.19564159 1.        ]]
consumer staples
[[1.         0.26495978]
 [0.26495978 1.        ]]
energy
[[1.         0.12327527]
 [0.12327527 1.        ]]
financials
[[1.         0.27399401]
 [0.27399401 1.        ]]
health care
[[1.        0.3356289]
 [0.3356289 1.       ]]
industrials
[[1.         0.24534735]
 [0.24534735 1.        ]]
information technology
[[1.         0.19807001]
 [0.19807001 1.        ]]
materials
[[1.         0.23926763]
 [0.23926763 1.        ]]
real estate
[[1.         0.21079601]
 [0.21079601 1.        ]]
utilities
[[1.         0.29551258]
 [0.29551258 1.        ]]


# Granger Causality

In [ ]:
from statsmodels.tsa.stattools import grangercausalitytests
for i in industry_list:
  print(i)
  grangercausalitytests(test[[i,'Sentiment_Score']], maxlag=3)

communications services

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0789  , p=0.7792  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.0803  , p=0.7769  , df=1
likelihood ratio test: chi2=0.0803  , p=0.7769  , df=1
parameter F test:         F=0.0789  , p=0.7792  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3590  , p=0.6989  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=0.7399  , p=0.6908  , df=2
likelihood ratio test: chi2=0.7383  , p=0.6913  , df=2
parameter F test:         F=0.3590  , p=0.6989  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4591  , p=0.7113  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=1.4371  , p=0.6969  , df=3
likelihood ratio test: chi2=1.4310  , p=0.6983  , df=3
parameter F test:         F=0.4591  , p=0.7113  , df_denom=161, df_num=3
consumer discretionary

Granger Causality
number of lags (no zero) 1
s

# Data Preprocessing (Negtive Percentage)


In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta

In [56]:
# calculate average sentiment score for each day
# The dataset misses the tweets data from March 29 2020 to March 30 2020
d = datetime(year=2020,month=3,day=17)
twitter = pd.read_csv("/content/drive/MyDrive/AN6201/corona_tweets_04.csv",header=None)
twitter.columns=['ID','Sentiment']
twitter.drop(columns=['ID'],inplace=True)
sad = twitter[twitter['Sentiment']<-0.05]
percentage = len(sad)/len(twitter)
dataframe = {'Date': [d+timedelta(days=4)], 'percentage':[percentage]}
sentiment = pd.DataFrame(dataframe)
sentiment

Date  percentage
0 2020-03-21    0.227725

In [57]:
# Sentiment Score from March 21 2020 to March 28 2020
percentage_list_4_11 = []
date_list_4_11 = []
for i in range(5,12):
  if i<=9:
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_0{i}.csv",header=None)
    df.columns=['ID','Sentiment']
    df.drop(columns=['ID'],inplace=True)
    sad = df[df['Sentiment']<-0.05]
    percentage = len(sad)/len(df)
    percentage_list_4_11.append(percentage)
    date = d+timedelta(days=i)
    date_list_4_11.append(date)
  else:
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_{i}.csv",header=None)
    df.columns=['ID','Sentiment']
    df.drop(columns=['ID'],inplace=True)
    sad = df[df['Sentiment']<-0.05]
    percentage = len(sad)/len(df)
    percentage_list_4_11.append(percentage)
    date = d+timedelta(days=i)
    date_list_4_11.append(date)
dataframe_4_11 = {'Date': date_list_4_11, 'percentage': percentage_list_4_11}
sentiment_4_11 = pd.DataFrame(dataframe_4_11)
sentiment_4_11 = sentiment.append(sentiment_4_11)
sentiment_4_11

Date  percentage
0 2020-03-21    0.227725
0 2020-03-22    0.247353
1 2020-03-23    0.237233
2 2020-03-24    0.215368
3 2020-03-25    0.206787
4 2020-03-26    0.174434
5 2020-03-27    0.208465
6 2020-03-28    0.230236

In [58]:
# Sentiment Score from March 30 2020 to June 26 2020
percentage_list_12_256 = []
date_list_12_256 = []
d = datetime(year=2020,month=3,day=18)
for i in range(12,257):
  if i == 223: # corona_tweets_223 lacks all the sentiment scores
    pass
  else: 
    df = pd.read_csv(f"/content/drive/MyDrive/AN6201/corona_tweets_{i}.csv",header=None)
    df.columns=['ID','Sentiment']
    df.drop(columns=['ID'],inplace=True)
    sad = df[df['Sentiment']<-0.05]
    percentage = len(sad)/len(df)
    percentage_list_12_256.append(percentage)
    date = d+timedelta(days=i)
    date_list_12_256.append(date)
dataframe_12_256 = {'Date': date_list_12_256, 'percentage': percentage_list_12_256}
sentiment_12_256 = pd.DataFrame(dataframe_12_256)
sentiment_4_256 = sentiment_4_11.append(sentiment_12_256)
sentiment_4_256

Date  percentage
0   2020-03-21    0.227725
0   2020-03-22    0.247353
1   2020-03-23    0.237233
2   2020-03-24    0.215368
3   2020-03-25    0.206787
..         ...         ...
239 2020-11-25    0.193956
240 2020-11-26    0.185505
241 2020-11-27    0.209007
242 2020-11-28    0.227161
243 2020-11-29    0.218545

[252 rows x 2 columns]

In [59]:
sentiment_4_256 = sentiment_4_11.append(sentiment_12_256)
sentiment_4_256

Date  percentage
0   2020-03-21    0.227725
0   2020-03-22    0.247353
1   2020-03-23    0.237233
2   2020-03-24    0.215368
3   2020-03-25    0.206787
..         ...         ...
239 2020-11-25    0.193956
240 2020-11-26    0.185505
241 2020-11-27    0.209007
242 2020-11-28    0.227161
243 2020-11-29    0.218545

[252 rows x 2 columns]

In [60]:
missing_days = {"Date": [datetime(year=2020,month=3,day=29),datetime(year=2020,month=10,day=27)],
                "percentage":[np.nan,np.nan]}
df_missing = pd.DataFrame(data = missing_days)
df_missing

Date  percentage
0 2020-03-29         NaN
1 2020-10-27         NaN

In [61]:
sentiment = sentiment_4_256.copy()
sentiment = sentiment.append(df_missing)
sentiment.index=sentiment['Date']
sentiment.sort_index(inplace=True)
sentiment.index = range(len(sentiment))
sentiment

Date  percentage
0   2020-03-21    0.227725
1   2020-03-22    0.247353
2   2020-03-23    0.237233
3   2020-03-24    0.215368
4   2020-03-25    0.206787
..         ...         ...
249 2020-11-25    0.193956
250 2020-11-26    0.185505
251 2020-11-27    0.209007
252 2020-11-28    0.227161
253 2020-11-29    0.218545

[254 rows x 2 columns]

In [62]:
print(sentiment[sentiment['Date']=="2020-03-29"].index) #8
print(sentiment[sentiment['Date']=="2020-10-27"].index) #220

Int64Index([8], dtype='int64')
Int64Index([220], dtype='int64')


In [63]:
sentiment['percentage'][8] = (sentiment['percentage'][7]+sentiment['percentage'][9])/2
sentiment['percentage'][220] = (sentiment['percentage'][219]+sentiment['percentage'][221])/2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [64]:
sentiment.to_csv("Sentiment.csv",index=None)

In [65]:
df = pd.read_csv("combine_final.csv")
df

Date  communications services  ...  S&P 500  Sentiment_Score
0     2020/3/23                   137.76  ...  2237.40         0.020968
1     2020/3/24                   145.77  ...  2447.33         0.025657
2     2020/3/25                   143.46  ...  2475.56         0.032868
3     2020/3/26                   152.14  ...  2630.07         0.049188
4     2020/3/27                   145.91  ...  2541.47         0.045155
..          ...                      ...  ...      ...              ...
166  2020/11/16                   214.49  ...  3626.91         0.083505
167  2020/11/17                   213.59  ...  3609.53         0.064463
168  2020/11/18                   211.52  ...  3567.79         0.062095
169  2020/11/19                   212.39  ...  3581.87         0.071393
170  2020/11/20                   211.22  ...  3557.54         0.066100

[171 rows x 14 columns]

In [66]:
df.dtypes

Date                        object
communications services    float64
consumer discretionary     float64
consumer staples           float64
energy                     float64
financials                 float64
health care                float64
industrials                float64
information technology     float64
materials                  float64
real estate                float64
utilities                  float64
S&P 500                    float64
Sentiment_Score            float64
dtype: object

In [67]:
df.Date = pd.to_datetime(df['Date'], errors='coerce')
df.dtypes

Date                       datetime64[ns]
communications services           float64
consumer discretionary            float64
consumer staples                  float64
energy                            float64
financials                        float64
health care                       float64
industrials                       float64
information technology            float64
materials                         float64
real estate                       float64
utilities                         float64
S&P 500                           float64
Sentiment_Score                   float64
dtype: object

In [68]:
sentiment.dtypes

Date          datetime64[ns]
percentage           float64
dtype: object

In [69]:
test = pd.merge(left = df, right = sentiment, how = 'left',left_on = 'Date',right_on='Date')
test

Date  communications services  ...  Sentiment_Score  percentage
0   2020-03-23                   137.76  ...         0.020968    0.237233
1   2020-03-24                   145.77  ...         0.025657    0.215368
2   2020-03-25                   143.46  ...         0.032868    0.206787
3   2020-03-26                   152.14  ...         0.049188    0.174434
4   2020-03-27                   145.91  ...         0.045155    0.208465
..         ...                      ...  ...              ...         ...
166 2020-11-16                   214.49  ...         0.083505    0.182904
167 2020-11-17                   213.59  ...         0.064463    0.191691
168 2020-11-18                   211.52  ...         0.062095    0.184542
169 2020-11-19                   212.39  ...         0.071393    0.183040
170 2020-11-20                   211.22  ...         0.066100    0.184246

[171 rows x 15 columns]

# Granger Causality 2


In [70]:
industry_list = ['communications services', 'consumer discretionary',
       'consumer staples', 'energy', 'financials', 'health care',
       'industrials', 'information technology', 'materials', 'real estate',
       'utilities']
for i in industry_list:
  print(i)
  print(np.corrcoef(test[i].to_numpy(), test.percentage))

communications services
[[ 1.         -0.07260701]
 [-0.07260701  1.        ]]
consumer discretionary
[[ 1.         -0.04297066]
 [-0.04297066  1.        ]]
consumer staples
[[ 1.         -0.13566176]
 [-0.13566176  1.        ]]
energy
[[ 1.         -0.04186336]
 [-0.04186336  1.        ]]
financials
[[ 1.         -0.08909544]
 [-0.08909544  1.        ]]
health care
[[ 1.         -0.14059785]
 [-0.14059785  1.        ]]
industrials
[[ 1.         -0.07955063]
 [-0.07955063  1.        ]]
information technology
[[ 1.         -0.04465406]
 [-0.04465406  1.        ]]
materials
[[ 1.         -0.06622755]
 [-0.06622755  1.        ]]
real estate
[[ 1.         -0.03970703]
 [-0.03970703  1.        ]]
utilities
[[ 1.         -0.13636502]
 [-0.13636502  1.        ]]


In [71]:
from statsmodels.tsa.stattools import grangercausalitytests
for i in industry_list:
  print(i)
  grangercausalitytests(test[[i,'percentage']], maxlag=5)

communications services

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0135  , p=0.9075  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.0138  , p=0.9065  , df=1
likelihood ratio test: chi2=0.0138  , p=0.9065  , df=1
parameter F test:         F=0.0135  , p=0.9075  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8658  , p=0.4226  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=1.7843  , p=0.4098  , df=2
likelihood ratio test: chi2=1.7750  , p=0.4117  , df=2
parameter F test:         F=0.8658  , p=0.4226  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6212  , p=0.6022  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=1.9447  , p=0.5840  , df=3
likelihood ratio test: chi2=1.9335  , p=0.5863  , df=3
parameter F test:         F=0.6212  , p=0.6022  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:       

In [ ]:
––≠≠